# Proyecto Análisis de Datos, Caso 2:
## Estudio sobre la calidad de aire en la Región Metropolitana de Santiago

En este proyecto, analizaremos los dataset de calidad de aire entregados por SINCA diariamente desde 2015 a 2025 en las comunas de Cerro Navia, El Bosque y Las Condes. 
Escogimos estas comunas para obtener una variación significativa en los datos (debido a lo diferente que son las comunas geográficamente), siendo nuestro único límite el de quedarse en Santiago, debido a que existían registros mas extensivos de esta ciudad.

Haremos un análisis descriptivo de los dataset, y luego, haremos un análisis inferencial para llegar a conclusiones significativas sobre los datos.

### Importar Librerías

In [25]:
import pandas as pd
import matplotlib as plt
import seaborn as sns
import scipy.stats as stats

### Carga y limpieza de datos

In [26]:
# Funciones para limpiar datos
def renamedb(df, column1, newcolumn1):
    ''' 
    Funcion para renombrar columna, con la antigua tomando el parametro 'column1' y el nuevo nombre de esta como 'newcolumn1'
    '''
    return df.rename(columns={f"{column1}":f"{newcolumn1}"})

Cerro Navia

In [27]:
naviaCO =pd.read_csv('Datos/cerro_navia/COCerroNavia.csv', sep=';')
display(naviaCO.head())
naviamp2_5 =pd.read_csv('Datos/cerro_navia/mp2.5CerroNavia.csv', sep=';')
display(naviamp2_5.head())
naviamp10 =pd.read_csv('Datos/cerro_navia/mp10CerroNavia.csv', sep=';')
display(naviamp10.head())
naviaNO2 =pd.read_csv('Datos/cerro_navia/NO2CerroNavia.csv', sep=';')
display(naviaNO2.head())
naviaNO =pd.read_csv('Datos/cerro_navia/NOCerroNavia.csv', sep=';')
display(naviaNO.head())
naviaNOx =pd.read_csv('Datos/cerro_navia/NOxCerroNavia.csv', sep=';')
display(naviaNOx.head())
naviaO3 =pd.read_csv('Datos/cerro_navia/O3CerroNavia.csv', sep=';')
display(naviaO3.head())

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"0,311059",NaN,NaN,NaN
1,150102,0,"0,313554",NaN,NaN,NaN
2,150103,0,"0,453158",NaN,NaN,NaN
3,150104,0,"0,382449",NaN,NaN,NaN
4,150105,0,"0,33844",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"11,4167",NaN,NaN,NaN
1,150102,0,"11,625",NaN,NaN,NaN
2,150103,0,"15,125",NaN,NaN,NaN
3,150104,0,"17,625",NaN,NaN,NaN
4,150105,0,"16,3333",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"23,3333",NaN,NaN,NaN
1,150102,0,"32,6591",NaN,NaN,NaN
2,150103,0,"44,2708",NaN,NaN,NaN
3,150104,0,"41,6666",NaN,NaN,NaN
4,150105,0,"40,8958",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"5,9546",NaN,NaN,NaN
1,150102,0,"10,5406",NaN,NaN,NaN
2,150103,0,"11,6892",NaN,NaN,NaN
3,150104,0,"8,44757",NaN,NaN,NaN
4,150105,0,"8,85443",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"3,01365",NaN,NaN,NaN
1,150102,0,"4,77319",NaN,NaN,NaN
2,150103,0,"5,52844",NaN,NaN,NaN
3,150104,0,"1,76569",NaN,NaN,NaN
4,150105,0,"4,07631",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"8,74979",NaN,NaN,NaN
1,150102,0,"15,2844",NaN,NaN,NaN
2,150103,0,"17,1725",NaN,NaN,NaN
3,150104,0,"10,124",NaN,NaN,NaN
4,150105,0,"12,92",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"19,7559",NaN,NaN,NaN
1,150102,0,"24,4797",NaN,NaN,NaN
2,150103,0,"25,1539",NaN,NaN,NaN
3,150104,0,"29,8737",NaN,NaN,NaN
4,150105,0,"23,4711",NaN,NaN,NaN

In [28]:
droppedcolumns = ["HORA (HHMM)", "Registros preliminares", "Registros no validados", "Unnamed: 5"]
def cleanNavia(df):

    df[["FECHA (YYMMDD)"]] = df[["FECHA (YYMMDD)"]].astype(str)
    df['FECHA (YYMMDD)'] = pd.to_datetime(df['FECHA (YYMMDD)'], format='%y%m%d')
    df2 = renamedb(df, "FECHA (YYMMDD)", "Fecha")
    df3 = df2.drop(droppedcolumns, axis=1, inplace=False)
    return df3                                                             

naviaCO = cleanNavia(naviaCO)
naviamp10 = cleanNavia(naviamp10)
naviamp2_5 = cleanNavia(naviamp2_5)
naviaNO2 = cleanNavia(naviaNO2)
naviaNO = cleanNavia(naviaNO)
naviaNOx = cleanNavia(naviaNOx)
naviaO3 = cleanNavia(naviaO3)

In [29]:
dfnavia = naviaCO
dfnavia = dfnavia.drop(["Registros validados"], axis=1, inplace=False)
dfnavia[['Fecha', 'CO']] = naviaCO[['Fecha', 'Registros validados']]
dfnavia[['MP10']] = naviamp10[['Registros validados']]
dfnavia[['MP2.5']] = naviamp2_5[['Registros validados']]
dfnavia[['NO2']] = naviaNO2[['Registros validados']]
dfnavia[['NO']] = naviaNO[['Registros validados']]
dfnavia[['NOx']] = naviaNOx[['Registros validados']]
dfnavia[['O3']] = naviaO3[['Registros validados']]

display(dfnavia)

,Fecha,CO,MP10,MP2.5,NO2,NO,NOx,O3
0,2015-01-01,"0,311059","23,3333","11,4167","5,9546","3,01365","8,74979","19,7559"
1,2015-01-02,"0,313554","32,6591","11,625","10,5406","4,77319","15,2844","24,4797"
2,2015-01-03,"0,453158","44,2708","15,125","11,6892","5,52844","17,1725","25,1539"
3,2015-01-04,"0,382449","41,6666","17,625","8,44757","1,76569","10,124","29,8737"
4,2015-01-05,"0,33844","40,8958","16,3333","8,85443","4,07631","12,92","23,4711"
...,...,...,...,...,...,...,...,...
3648,2024-12-27,"0,23",34,8,"7,95","6,32302","14,2701",20
3649,2024-12-28,"0,21",32,6,"6,36","4,58061","10,9368",23
3650,2024-12-29,"0,24",35,9,"6,21","4,50652","10,7157",26
3651,2024-12-30,"0,21",43,11,"7,89","6,88325","14,7775",21
3652,2024-12-31,"0,26",38,10,"7,2","7,06961","14,2734",18

Este será el dataframe usado para el análisis de datos del Cerro Navia.

El Bosque

In [30]:
elBosqueCO =pd.read_csv('Datos/el_bosque/COElBosque.csv', sep=';')
display(elBosqueCO.head())
elBosquemp2_5 =pd.read_csv('Datos/el_bosque/mp2.5ElBosque.csv', sep=';')
display(elBosquemp2_5.head())
elBosquemp10 =pd.read_csv('Datos/el_bosque/mp10ElBosque.csv', sep=';')
display(elBosquemp10.head())
elBosqueNO2 =pd.read_csv('Datos/el_bosque/NO2ElBosque.csv', sep=';')
display(elBosqueNO2.head())
elBosqueNO =pd.read_csv('Datos/el_bosque/NOElBosque.csv', sep=';')
display(elBosqueNO.head())
elBosqueNOx =pd.read_csv('Datos/el_bosque/NOxElBosque.csv', sep=';')
display(elBosqueNOx.head())
elBosqueO3 =pd.read_csv('Datos/el_bosque/O3ElBosque.csv', sep=';')
display(elBosqueO3.head())

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,NaN,NaN,"0,865583",NaN
1,150102,0,NaN,NaN,"0,94251",NaN
2,150103,0,NaN,NaN,"0,983727",NaN
3,150104,0,NaN,NaN,"1,05342",NaN
4,150105,0,NaN,NaN,"0,95801",NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"11,4167",NaN,NaN,NaN
1,150102,0,"11,625",NaN,NaN,NaN
2,150103,0,"15,125",NaN,NaN,NaN
3,150104,0,"17,625",NaN,NaN,NaN
4,150105,0,"16,3333",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"25,8913",NaN,NaN,NaN
1,150102,0,"41,5",NaN,NaN,NaN
2,150103,0,"55,6875",NaN,NaN,NaN
3,150104,0,"54,5416",NaN,NaN,NaN
4,150105,0,"52,5833",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"7,71136",NaN,NaN,NaN
1,150102,0,"17,6479",NaN,NaN,NaN
2,150103,0,"18,5216",NaN,NaN,NaN
3,150104,0,"14,9414",NaN,NaN,NaN
4,150105,0,"14,9531",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"1,19703",NaN,NaN,NaN
1,150102,0,"8,90382",NaN,NaN,NaN
2,150103,0,"9,18172",NaN,NaN,NaN
3,150104,0,"5,26273",NaN,NaN,NaN
4,150105,0,"6,62319",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"8,90294",NaN,NaN,NaN
1,150102,0,"26,5518",NaN,NaN,NaN
2,150103,0,"27,7034",NaN,NaN,NaN
3,150104,0,"20,2041",NaN,NaN,NaN
4,150105,0,"21,5762",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"15,832",NaN,NaN,NaN
1,150102,0,"18,1103",NaN,NaN,NaN
2,150103,0,"21,9386",NaN,NaN,NaN
3,150104,0,"25,3021",NaN,NaN,NaN
4,150105,0,"17,764",NaN,NaN,NaN

In [31]:
droppedcolumns = ["HORA (HHMM)", "Registros preliminares", "Registros no validados", "Unnamed: 5"]
def cleanElBosque(df):

    df[["FECHA (YYMMDD)"]] = df[["FECHA (YYMMDD)"]].astype(str)
    df['FECHA (YYMMDD)'] = pd.to_datetime(df['FECHA (YYMMDD)'], format='%y%m%d')
    df2 = renamedb(df, "FECHA (YYMMDD)", "Fecha")
    df3 = df2.drop(droppedcolumns, axis=1, inplace=False)
    return df3 

elBosqueCO = cleanElBosque(elBosqueCO)
elBosquemp10 = cleanElBosque(elBosquemp10)
elBosquemp2_5 = cleanElBosque(elBosquemp2_5)
elBosqueNO2 = cleanElBosque(elBosqueNO2)
elBosqueNO = cleanElBosque(elBosqueNO)
elBosqueNOx = cleanElBosque(elBosqueNOx)
elBosqueO3 = cleanElBosque(elBosqueO3)

In [33]:
dfElBosque = elBosqueCO
dfElBosque = dfElBosque.drop(["Registros validados"], axis=1, inplace=False)
dfElBosque[['Fecha', 'CO']] = elBosqueCO[['Fecha', 'Registros validados']]
dfElBosque[['MP10']] = elBosquemp10[['Registros validados']]
dfElBosque[['MP2.5']] = elBosquemp2_5[['Registros validados']]
dfElBosque[['NO2']] = elBosqueNO2[['Registros validados']]
dfElBosque[['NO']] = elBosqueNO[['Registros validados']]
dfElBosque[['NOx']] = elBosqueNOx[['Registros validados']]
dfElBosque[['O3']] = elBosqueO3[['Registros validados']]

display(dfnavia)
display(dfElBosque)

,Fecha,CO,MP10,MP2.5,NO2,NO,NOx,O3
0,2015-01-01,"0,311059","23,3333","11,4167","5,9546","3,01365","8,74979","19,7559"
1,2015-01-02,"0,313554","32,6591","11,625","10,5406","4,77319","15,2844","24,4797"
2,2015-01-03,"0,453158","44,2708","15,125","11,6892","5,52844","17,1725","25,1539"
3,2015-01-04,"0,382449","41,6666","17,625","8,44757","1,76569","10,124","29,8737"
4,2015-01-05,"0,33844","40,8958","16,3333","8,85443","4,07631","12,92","23,4711"
...,...,...,...,...,...,...,...,...
3648,2024-12-27,"0,23",34,8,"7,95","6,32302","14,2701",20
3649,2024-12-28,"0,21",32,6,"6,36","4,58061","10,9368",23
3650,2024-12-29,"0,24",35,9,"6,21","4,50652","10,7157",26
3651,2024-12-30,"0,21",43,11,"7,89","6,88325","14,7775",21
3652,2024-12-31,"0,26",38,10,"7,2","7,06961","14,2734",18

          Fecha    CO     MP10    MP2.5      NO2       NO      NOx       O3
0    2015-01-01   NaN  25,8913  11,4167  7,71136  1,19703  8,90294   15,832
1    2015-01-02   NaN     41,5   11,625  17,6479  8,90382  26,5518  18,1103
2    2015-01-03   NaN  55,6875   15,125  18,5216  9,18172  27,7034  21,9386
3    2015-01-04   NaN  54,5416   17,625  14,9414  5,26273  20,2041  25,3021
4    2015-01-05   NaN  52,5833  16,3333  14,9531  6,62319  21,5762   17,764
...         ...   ...      ...      ...      ...      ...      ...      ...
3648 2024-12-27  0,41       42        8      NaN      NaN      NaN       22
3649 2024-12-28  0,37       38        6      NaN      NaN      NaN       24
3650 2024-12-29  0,36       40        9      NaN      NaN      NaN       26
3651 2024-12-30  0,37       52       11      NaN      NaN      NaN       22
3652 2024-12-31  0,39       44       10      NaN      NaN      NaN       19

[3653 rows x 8 columns]

Las Condes