# Proyecto Análisis de Datos, Caso 2:
## Estudio sobre la calidad de aire en la Región Metropolitana de Santiago

En este proyecto, analizaremos los dataset de calidad de aire entregados por SINCA diariamente desde 2015 a 2025 en las comunas de Cerro Navia, El Bosque y Las Condes. 
Escogimos estas comunas para obtener una variación significativa en los datos (debido a lo diferente que son las comunas geográficamente), siendo nuestro único límite el de quedarse en Santiago, debido a que existían registros mas extensivos de esta ciudad.

Haremos un análisis descriptivo de los dataset, y luego, haremos un análisis inferencial para llegar a conclusiones significativas sobre los datos.

### Importar Librerías

In [127]:
import pandas as pd
import matplotlib as plt
import seaborn as sns
import scipy.stats as stats

### Carga y limpieza de datos

In [128]:
# Funciones para limpiar datos
def renamedb(df, column1, newcolumn1):
    ''' 
    Funcion para renombrar columna, con la antigua tomando el parametro 'column1' y el nuevo nombre de esta como 'newcolumn1'
    '''
    return df.rename(columns={f"{column1}":f"{newcolumn1}"})

Cerro Navia

In [129]:
naviaCO =pd.read_csv('Datos/cerro_navia/COCerroNavia.csv', sep=';')
display(naviaCO.head())
naviamp2_5 =pd.read_csv('Datos/cerro_navia/mp2.5CerroNavia.csv', sep=';')
display(naviaCO.head())
naviamp10 =pd.read_csv('Datos/cerro_navia/mp10CerroNavia.csv', sep=';')
display(naviaCO.head())
naviaNO2 =pd.read_csv('Datos/cerro_navia/NO2CerroNavia.csv', sep=';')
display(naviaCO.head())
naviaNO =pd.read_csv('Datos/cerro_navia/NOCerroNavia.csv', sep=';')
display(naviaCO.head())
naviaNOx =pd.read_csv('Datos/cerro_navia/NOxCerroNavia.csv', sep=';')
display(naviaCO.head())
naviaO3 =pd.read_csv('Datos/cerro_navia/O3CerroNavia.csv', sep=';')
display(naviaCO.head())

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"0,311059",NaN,NaN,NaN
1,150102,0,"0,313554",NaN,NaN,NaN
2,150103,0,"0,453158",NaN,NaN,NaN
3,150104,0,"0,382449",NaN,NaN,NaN
4,150105,0,"0,33844",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"0,311059",NaN,NaN,NaN
1,150102,0,"0,313554",NaN,NaN,NaN
2,150103,0,"0,453158",NaN,NaN,NaN
3,150104,0,"0,382449",NaN,NaN,NaN
4,150105,0,"0,33844",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"0,311059",NaN,NaN,NaN
1,150102,0,"0,313554",NaN,NaN,NaN
2,150103,0,"0,453158",NaN,NaN,NaN
3,150104,0,"0,382449",NaN,NaN,NaN
4,150105,0,"0,33844",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"0,311059",NaN,NaN,NaN
1,150102,0,"0,313554",NaN,NaN,NaN
2,150103,0,"0,453158",NaN,NaN,NaN
3,150104,0,"0,382449",NaN,NaN,NaN
4,150105,0,"0,33844",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"0,311059",NaN,NaN,NaN
1,150102,0,"0,313554",NaN,NaN,NaN
2,150103,0,"0,453158",NaN,NaN,NaN
3,150104,0,"0,382449",NaN,NaN,NaN
4,150105,0,"0,33844",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"0,311059",NaN,NaN,NaN
1,150102,0,"0,313554",NaN,NaN,NaN
2,150103,0,"0,453158",NaN,NaN,NaN
3,150104,0,"0,382449",NaN,NaN,NaN
4,150105,0,"0,33844",NaN,NaN,NaN

,FECHA (YYMMDD),HORA (HHMM),Registros validados,Registros preliminares,Registros no validados,Unnamed: 5
0,150101,0,"0,311059",NaN,NaN,NaN
1,150102,0,"0,313554",NaN,NaN,NaN
2,150103,0,"0,453158",NaN,NaN,NaN
3,150104,0,"0,382449",NaN,NaN,NaN
4,150105,0,"0,33844",NaN,NaN,NaN

In [130]:
droppedcolumns = ["HORA (HHMM)", "Registros preliminares", "Registros no validados", "Unnamed: 5"]
def cleanNavia(df):

    df[["FECHA (YYMMDD)"]] = df[["FECHA (YYMMDD)"]].astype(str)
    df['FECHA (YYMMDD)'] = pd.to_datetime(df['FECHA (YYMMDD)'], format='%y%m%d')
    df2 = renamedb(df, "FECHA (YYMMDD)", "Fecha")
    df3 = df2.drop(droppedcolumns, axis=1, inplace=False)
    return df3

naviaCO = cleanNavia(naviaCO)
naviamp10 = cleanNavia(naviamp10)
naviamp2_5 = cleanNavia(naviamp2_5)
naviaNO2 = cleanNavia(naviaNO2)
naviaNO = cleanNavia(naviaNO)
naviaNOx = cleanNavia(naviaNOx)
naviaO3 = cleanNavia(naviaO3)

In [131]:
naviamp10

          Fecha Registros validados
0    2015-01-01             23,3333
1    2015-01-02             32,6591
2    2015-01-03             44,2708
3    2015-01-04             41,6666
4    2015-01-05             40,8958
...         ...                 ...
3648 2024-12-27                  34
3649 2024-12-28                  32
3650 2024-12-29                  35
3651 2024-12-30                  43
3652 2024-12-31                  38

[3653 rows x 2 columns]

El Bosque

Las Condes